version: "3.8"

services:
  audiobookshelf_namer:
    image: ghcr.io/druidblack/secret-santa-bot:latest
    container_name: secret-santa-bot
    restart: unless-stopped

    environment:
      TOKEN: "Bot Token"
      STATE_FILE: "/data/secret_santa_state.json"

    volumes:
      - ./abs-namer-data:/data
