version: "3.9"

services:
  secret-santa-bot:
    image: ghcr.io/druidblack/secret-santa-bot:latest
    container_name: secret-santa-bot
    restart: unless-stopped

    environment:
      TOKEN: "bot token"

    volumes:
      - ./secret_santa_state.json:/app/secret_santa_state.json